"""empty message

Revision ID: 4046329d662e
Revises: 4f0843b96480
Create Date: 2024-10-18 17:48:24.795146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4046329d662e'
down_revision = '4f0843b96480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
