"""empty message

Revision ID: 4f0843b96480
Revises: 42b4e95a7bbb
Create Date: 2024-10-17 10:12:26.755608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f0843b96480'
down_revision = '42b4e95a7bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'SUPPORT', 'USER', name='userroleenum'),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ADMIN', 'SUPPORT', 'USER', name='userroleenum'),
               existing_nullable=True)

    # ### end Alembic commands ###
