"""empty message

Revision ID: d3185e6aa904
Revises: d8064a3517be
Create Date: 2024-10-28 16:02:36.904794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3185e6aa904'
down_revision = 'd8064a3517be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('approver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('approver')
        batch_op.drop_column('designation')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###
