"""empty message

Revision ID: d8064a3517be
Revises: f4dfe80efb5f
Create Date: 2024-10-23 20:07:09.688116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8064a3517be'
down_revision = 'f4dfe80efb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
